# Generated by Django 5.2.5 on 2025-09-03 10:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=150, null=True, unique=True)),
                ('db_name', models.CharField(max_length=100)),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=100)),
                ('db_host', models.CharField(default='localhost', max_length=100)),
                ('db_port', models.CharField(default='5432', max_length=10)),
                ('db_type', models.CharField(choices=[('self_hosted', 'Self Hosted'), ('client_hosted', 'Client Hosted')], default='self_hosted', max_length=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='uniq_userdatabase_username_ci')],
            },
        ),
    ]
